baseURL = 'https://meiwangmw.github.io/'
languageCode = 'en-us'
title = 'Mei Wang'
theme = "void"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Social media links
[params]
  [params.avatar]
    url = "https://avatars.githubusercontent.com/u/234100657?v=4"
  
  [params.social]
    linkedin = "https://www.linkedin.com/in/mei-wang-958825139"
    twitter = "https://x.com/Mei_Wang567"
    facebook = ""
    scholar = ""
    umn = "https://carlsonschool.umn.edu/faculty/mei-wang"
    email = "meiwang.mwang@gmail.com"

# Main menu
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'CV'
pageRef = '/cv'
weight = 20

[[menus.main]]
name = 'Research'
pageRef = '/research'
weight = 30