baseURL = 'https://meiwangmw.github.io/'
languageCode = 'en-us'
title = 'Mei Wang'
theme = "void"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Social media links
[params]
  [params.avatar]
    url = "https://avatars.githubusercontent.com/u/234100657?v=4"
  
  [params.social]
    linkedin = "https://linkedin.com/in/your-profile"
    twitter = "https://twitter.com/your-handle"
    facebook = "https://facebook.com/your-profile"
    scholar = "https://scholar.google.com/citations?user=your-id"
    email = "your-email@example.com"

# Main menu
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'CV'
pageRef = '/posts/cv'
weight = 20

[[menus.main]]
name = 'Research'
pageRef = '/research'
weight = 30