baseURL = 'https://meiwangmw.github.io/'
languageCode = 'en-us'
title = 'Mei Wang'
theme = "void"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Social media links
[params]
  [params.social]
    github = "https://github.com/meiwangmw"
    zhihu = "https://www.linkedin.com/in/mei-wang-958825139/"
    email = "meiwang.mwang@gmail.com"
  [params.avatar]
    url = "https://avatars.githubusercontent.com/u/234100657?v=4"

# Main menu
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40