name = 'Void'
license = 'MIT'
licenselink = 'https://github.com/Daucloud/hugo-theme-void/blob/main/LICENSE'
description = 'A clean, modern Hugo blog theme built with Tailwind CSS'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/Daucloud/hugo-theme-void'

# If you have a running demo of the theme
# demosite = 'https://daucloud.github.io/hugo-theme-void'

# Taxonomy terms
tags = ['blog', 'responsive', 'personal', 'light', 'tailwind', 'minimal']
features = ['responsive', 'tailwind css', 'blog', 'light mode', 'social icons', 'code highlighting', 'clean design']

# If you have a running demo of the theme.
demosite = "https://www.daucloud.com"

# If the theme has a single author
[author]
  name = 'Daucloud'
  homepage = 'https://github.com/Daucloud'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
